version: 2.1

# Caching between jobs
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: mkdir -p workspace
      - run: echo  "HELLLLLOOOOO WWWWOOOORRRRLLLLLLD" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
<<<<<<< HEAD
          at: ~/
          # root: ~/
          # paths:
          #   - output.txt
      - run: cat ~/output.txt
||||||| e6a9141
          root: ~/
          paths:
            - output.txt
      - run: cat output.txt
=======
          at: /tmp/workspace
          #root: ~/
          #paths:
          #  - output.txt
      - run: cat /tmp/workspace/output.txt
>>>>>>> df1e776c5026ce581da2c04403e1f1a2bc74c936

workflows:
  default:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
          - save_hello_world_output
